packages:
    - .

onlyBuiltDependencies:
    - better-sqlite3
    - canvas
    - esbuild
    - sharp
    - tesseract.js
    - core-js
    - onnxruntime-node
    - protobufjs
    - "@tensorflow/tfjs-node"
