packages:
    - "."

allowBuilds:
    "@google/genai": true
    "@tensorflow/tfjs-node": true
    better-sqlite3: true
    canvas: true
    core-js: true
    esbuild: true
    onnxruntime-node: true
    protobufjs: true
    sharp: true
    tesseract.js: true

overrides:
    onnxruntime-web: 1.24.1
